# Generated by Django 6.0.6 on 2026-07-13 11:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_optional_event_for_shared_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentqrcode',
            name='qr_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_image'),
        ),
        migrations.AlterField(
            model_name='promoterpayment',
            name='payment_screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='payment_screenshot'),
        ),
    ]
