# Generated by Django 6.0.6 on 2026-07-13 11:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_gallery_caption_group_custom_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
