# Generated by Django 6.0.6 on 2026-07-13 11:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestlists', '0002_optional_admin_guest_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='payment_screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='payment_screenshot'),
        ),
    ]
