# Generated by Django 6.0.6 on 2026-07-12 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('FACEBOOK', 'Facebook'), ('OTHER', 'Other')], default='INSTAGRAM', max_length=15)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('deliverables', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('CONTACTED', 'Contacted'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONTACTED', max_length=15)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencers', to='events.event')),
            ],
        ),
    ]
